name: PrePublish

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  prePublish:
    name: PrePublish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > .npmrc

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: true

      - name: Check release plan
        #  If a version plan file does not exist, the command will print an error message and return a non-zero exit code
        run: npx nx release plan:check

      - name: Build all packages
        run: npx nx run-many -t build

      - name: Bump prerelease version
        run: npx nx release version --specifier prerelease --preid alpha

      - name: Publish packages
        run: pnpm publish -r --access public --no-git-checks
