name: Publish

on:
  workflow_dispatch:
  push:
    branches: master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: true

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          publish: pnpm run publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
